spring.application.name=plantify
spring.mvc.problemdetails.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=true
springdoc.swagger-ui.enabled=true

logging.level.com.zaxxer.hikari=WARN
logging.level.nh.demo.plantify.PlantifyApplication=WARN
logging.level.org.springframework.data=WARN
logging.level.org.springdoc.core=WARN
logging.level.org.springframework.scheduling=WARN
logging.level.org.springframework.boot.jpa=WARN
logging.level.org.springframework.web.servlet=WARN
logging.level.org.springframework.boot.devtools=WARN
logging.level.org.springframework.orm.jpa=WARN
logging.level.org.apache.catalina=WARN
logging.level.org.hibernate.orm.connections=WARN
logging.level.org.springframework.boot.actuate=WARN
logging.level.org.hibernate.orm=WARN

logging.level.org.flywaydb.core=WARN


management.tracing.sampling.probability=1
management.otlp.metrics.export.enabled=true
management.tracing.export.enabled=false
#management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans

logging.level.nh.demo.plantify=DEBUG

# OpenAPI / Swagger UI
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true

# MODULITH
spring.modulith.events.jdbc.schema-initialization.enabled=true
management.endpoints.web.exposure.include=health,modulith
# Normalerweise nur fuer Tests, aber hier fuer "shift-by"-Demo
spring.modulith.moments.enable-time-machine=true

spring.modulith.runtime.flyway-enabled=false
spring.modulith.events.republish-outstanding-events-on-restart=true


